### ISSUE TITLE
No UI on port 8091

### ISSUE THREAD

**Issue by DaveDixon** [zwave-js/zwave-js-ui#2997] opened 2023-03-13 03:10 UTC
System journal from last startup about 30 minutes ago:

>Mar 12 20:01:35 <node> zwave-js-ui.zwave-js-ui[19760]: 2023-03-12 20:01:35.224 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
>Mar 12 20:01:42 <node> zwave-js-ui.zwave-js-ui[19760]: 2023-03-12 20:01:42.441 ERROR Z-WAVE-SERVER: listen EADDRINUSE: address already in use 0.0.0.0:8091
>Mar 12 20:01:42 <node> zwave-js-ui.zwave-js-ui[19760]: Error: listen EADDRINUSE: address already in use 0.0.0.0:8091
>Mar 12 20:01:42 <node> zwave-js-ui.zwave-js-ui[19760]: 2023-03-12 20:01:42.441 ERROR Z-WAVE-SERVER: listen EADDRINUSE: address already in use 0.0.0.0:8091
>Mar 12 20:01:42 <node> zwave-js-ui.zwave-js-ui[19760]: Error: listen EADDRINUSE: address already in use 0.0.0.0:8091
>Mar 12 20:01:42 <node> zwave-js-ui.zwave-js-ui[19760]: 2023-03-12 20:01:42.441 ERROR Z-WAVE: Failed to start zwave-js server: listen EADDRINUSE: address already in use 0.0.0.0:8091
>Mar 12 20:05:42 <node> zwave-js-ui.zwave-js-ui[19973]: 2023-03-12 20:05:42.164 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP

netstat says no one is using port 8091. headless server, so I can only check the port remotely. ufw is open for tcp on port 8091. url times out. other ports on same ip address work fine, including homeassistant.

zwave-js-ui version 10.10.0 (snap installation)
Ubuntu 22.04.2
Homeassistant 2022.6
Nodejs v16.15.1

Suggestions, anyone?

Thanks!

**Comment by DaveDixon** [comment] 2023-03-13 03:22
zwave-js-ui seems to be playing well with homeassistant, btw..

**Comment by DaveDixon** [comment] 2023-03-13 08:14
Sorry, that was the wrong restart. This is what I get
> Mar 12 20:08:19 <node> zwave-js-ui.zwave-js-ui[20114]: 2023-03-12 20:08:19.450 INFO Z-WAVE-SERVER: ZwaveJS server listening on 0.0.0.0:3000
Otherwise it wouldn't be working with homeassistant, I suppose. But nothing in the log about port 8091, the ui, or serving http.

**Comment by DaveDixon** [comment] 2023-03-13 08:17
Incidentally (not obviously connected but idk) I get this exception at startup

>Mar 12 20:08:14 mills audit[20114]: AVC apparmor="DENIED" operation="mkdir" profile="snap.zwave-js-ui.zwave-js-ui" name="/var/snap/zwave-js-ui/122/" pid=20114 comm="node" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
>Mar 12 20:08:14 mills kernel: audit: type=1400 audit(1678673294.390:969): apparmor="DENIED" operation="mkdir" profile="snap.zwave-js-ui.zwave-js-ui" name="/var/snap/zwave-js-ui/122/" pid=20114 comm="node" requested_mask="c" denied_mask="c" fsuid=0 ouid=0

**Comment by robertsLando** [comment] 2023-03-13 08:17
Seems a snap issue, @jmgiaever any clue?

**Comment by jmgiaever** [comment] 2023-03-13 08:45
Hi,

Looks like it doesn't have the correct rights to create files within the isolated mount. 

That can be caused by rights issues in the OS, or a bad snapd setup. 

Which OS are you running?

How are you trying to start ZUI? Have you enabled it as a daemon (`sudo zwave-js-ui.enable` or `sudo snap enable zwave-js-ui`) or just running it (e.g `sudo zwave-js-ui.exec`)?

Are you using sudo?

**Comment by DaveDixon** [comment] 2023-03-13 09:08
Ubuntu 22.04.2. Running a systemd deamon.

**Comment by jmgiaever** [comment] 2023-03-13 09:34
Can you elaborate?

**Comment by DaveDixon** [comment] 2023-03-13 16:52
I have a daemon running under systemd, so I guess that means I ran sudo zwave-js-ui.enable or equivalent at some point. It started out as ZWavejs2Mqtt and migrated, so the details are hazy. Just to be sure, I stopped the daemon and ran sudo zwave-js-ui.enable and the outcome was the same as it was before. It runs normally, no error messages, but no log messages about serving http on port 8091, either.

**Comment by robertsLando** [comment] 2023-03-21 13:41
Hi Dave, have you been able to fix your problem? I'm sorry but I cannot give you so much support regarding snap side

**Comment by DaveDixon** [comment] 2023-03-21 18:41
Daniel,

Thanks for asking.

No, nothing seems to make it work. Soon it won't matter. I'm about to 
switch to HA OS on a Raspberry Pi for unrelated reasons. I really liked 
having HA on a Linux server, but it looks like HA OS gets all the good 
stuff anymore. So I'm hoping I can expect more reliability, anyway.

Thanks again,

-dave

**Comment by robertsLando** [comment] 2023-03-22 07:10
OK let me know if with that everything works, I really have no clue what's the error here but for sure nothing strictly related to zui so closing this for now, feel free to reopen if needed

**Closed** 2023-03-22 07:10 UTC
Labels: question
