### ISSUE TITLE
Will not display in Firefox or Edge since update to 8.25

### ISSUE THREAD

**Issue by ornative** [zwave-js/zwave-js-ui#3266] opened 2023-09-06 21:49 UTC
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.25.0.c77db28

### ZwaveJS version

11.14.0

### Describe the bug

 Firefox does not display initial screen at all.  

### To Reproduce

Running Firefox 117.0 (64-bit) with no extensions and opening site results in no display.

### Expected behavior

To display opening screen as it did in previous version.  This was not a problem before updating Zwave -js-ui today.

### Additional context

Loading module from “http://192.168.5.100:8091/control-panel/assets/index-06cc9b56.js” was blocked because of a disallowed MIME type (“text/html”).
[control-panel](http://192.168.5.100:8091/control-panel/)
Loading failed for the module with source “http://192.168.5.100:8091/control-panel/assets/index-06cc9b56.js”. [control-panel:32:69](http://192.168.5.100:8091/control-panel/)
The resource from “http://192.168.5.100:8091/control-panel/assets/index-35a64e76.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[control-panel](http://192.168.5.100:8091/control-panel/)
The resource from “http://192.168.5.100:8091/control-panel/registerSW.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[control-panel](http://192.168.5.100:8091/control-panel/)
Loading failed for the <script> with source “http://192.168.5.100:8091/control-panel/registerSW.js”.

​

​

**Comment by robertsLando** [comment] 2023-09-07 06:24
@ornative Try to remove `/control-panel/...` from the url

**Comment by robertsLando** [comment] 2023-09-07 06:30
Duplicate of #3267

**Closed by robertsLando** 2023-09-07 06:30 UTC
Labels: bug
