### ISSUE TITLE
Z-Wave JS UI and Rind KeyPad v2

### ISSUE THREAD

**Issue by DoughyKitty** [zwave-js/zwave-js-ui#3167] opened 2023-07-13 22:37 UTC
Add-on: Z-Wave JS UI

Add-on Version: 1.14.0
System: Home Assistant OS 10.3 (amd64/qemuz86-64)
Home Assistant Core: 2023.7.1
Home Assistant Supervisor: 2023.07.1

Whenever JS UI interviews the Ring Keypad V2, it will pin at 50% add-on cpu usage and keep constantly restarting the add-on.

The normal Z-Wave JS appears to be able to interview the node fine, but it is only JS UI that has issues.

Oddly enough, I added the Keypad to via the JS UI QR Code, which functioned correctly.

> 2023-07-13T22:29:15.912Z CNTRLR » [Node 021] querying parameter #14 information...
> 2023-07-13T22:29:15.964Z CNTRLR « [Node 021] received information for parameter #14:
>                                   value format:        UnsignedInteger
>                                   value size:          1 bytes
>                                   min value:           0
>                                   max value:           100
>                                   default value:       20
>                                   is read-only:        false
>                                   is advanced (UI):    true
>                                   has bulk support:    true
>                                   alters capabilities: false
> 2023-07-13T22:29:15.966Z CNTRLR » [Node 021] querying parameter #15 information...
> 2023-07-13T22:29:16.015Z CNTRLR « [Node 021] received information for parameter #15:
>                                   value format:        UnsignedInteger
                                  value size:          1 bytes
                                  min value:           0
                                  max value:           1
                                  default value:       1
                                  is read-only:        false
                                  is advanced (UI):    true
                                  has bulk support:    true
                                  alters capabilities: false
2023-07-13T22:29:16.016Z CNTRLR » [Node 021] querying parameter #16 information...
2023-07-13T22:29:16.069Z CNTRLR « [Node 021] received information for parameter #16:
                                  value format:        UnsignedInteger
                                  value size:          1 bytes
                                  min value:           0
                                  max value:           255
                                  default value:       50
                                  is read-only:        false
                                  is advanced (UI):    true
                                  has bulk support:    true
                                  alters capabilities: false
2023-07-13T22:29:16.070Z CNTRLR » [Node 021] querying parameter #17 information...
2023-07-13T22:29:16.121Z CNTRLR « [Node 021] received information for parameter #17:
                                  value format:        UnsignedInteger
                                  value size:          1 bytes
                                  min value:           0
                                  max value:           100
                                  default value:       30
                                  is read-only:        false
                                  is advanced (UI):    true
                                  has bulk support:    true
                                  alters capabilities: false`

**Comment by DoughyKitty** [comment] 2023-07-14 00:09
Interesting. If I put it in the microwave, it will finish interviewing all the other nodes.. But decide the keypad is dead. 

After Z-Wave JS UI finishes loading and labeling it as dead, I can then take it out of the microwave and it will function fine.

**Comment by robertsLando** [comment] 2023-07-14 07:09
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

**Comment by miniminne** [comment] 2023-07-15 04:57
[docker_log_zwave.log](https://github.com/zwave-js/zwave-js-ui/files/12060408/docker_log_zwave.log)
I'm having the same issue, but with HA's limitations I was able to get this log in debug mode. 

Node 5 is my alarm panel, and it cuts off when the addon/container crashes and restarts.

**Comment by robertsLando** [comment] 2023-07-15 06:22
CC @AlCalzone

**Comment by AlCalzone** [comment] 2023-07-15 09:50
Another duplicate of https://github.com/zwave-js/node-zwave-js/issues/6012

**Comment by AlCalzone** [comment] 2023-07-18 15:18
This will be fixed in driver version 11.5.1

**Comment by robertsLando** [comment] 2023-07-25 14:35
Fixed in 8.21.1

**Closed by robertsLando** 2023-07-25 14:35 UTC
Labels: question
