### ISSUE TITLE
[question] zwave-js-ui fatal error on docker creation  #FailureMessage Object: 0x7ef6549c

### ISSUE THREAD

**Issue by uberdorf** [zwave-js/zwave-js-ui#2724] opened 2022-10-11 20:48 UTC
Updated from ZWavejs2Mqtt to zwave-js-ui by adjusting docker-compose.yml
Running Raspbian GNU/Linux 10 (buster)

After update I get the following error message.
Any  suggestions on what might cause this?
Reverting to ZWavejs2Mqtt gives the same error message

~/docker/zwave-js-ui $ sudo docker-compose up
Creating zwave-js-ui ... done
Attaching to zwave-js-ui
zwave-js-ui    | 
zwave-js-ui    | 
zwave-js-ui    | #
zwave-js-ui    | # Fatal error in , line 0
zwave-js-ui    | # unreachable code
zwave-js-ui    | #
zwave-js-ui    | #
zwave-js-ui    | #
zwave-js-ui    | #FailureMessage Object: 0x7ef6549c

docker-compose.yml

version: '3.7'
services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Europe/Amsterdam
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/ttyAMA0:/dev/zwave'
    volumes:
      - zwave-config:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config

**Comment by robertsLando** [comment] 2022-10-12 06:21
Duplicate of #2725 please follow updates there

**Closed by robertsLando** 2022-10-12 06:21 UTC
Labels: question
