### ISSUE TITLE
Error while fetching store files: EPERM

### ISSUE THREAD

**Issue by jriker1** [zwave-js/zwave-js-ui#2937] opened 2023-02-01 17:16 UTC
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

PKG executable

### Z-Wave JS UI version

8.8.0

### ZwaveJS version

10.4.0

### Describe the bug

Not sure if it was when archiving but have Z-WaveJS UI running on Windows 2022 with Hyper-V role.  There is a log from teh 29th in the log folder as of 2/1 and ther eis also a tar.gz file for that day.  I can't access that log file or change ownership.  When I go to the Store tab I get:

Error while fetching store files: EPERM: operation not permitted, lstat 'E:\Z-WaveJSUI\store\logs\zwavejs_2023-01-29.log'

I have since deleted that log file but the system is still complaining about it when I open up the Z-WaveJS UI > Store location again fresh in a browser.

### To Reproduce

Launch Z-WaveJS UI  and click on Store.

### Expected behavior

It shows a tree of files/folders.

**Comment by robertsLando** [comment] 2023-02-02 07:24
I'm not a windows expert but how did you start zui? It could be you runned it with admin privileges and that created that file, try to right click on the file to check its ownership and fix it. Also be sure you are not running zui as administrator

**Comment by jriker1** [comment] 2023-02-02 14:16
I am running the application as a domain admin so anything being done with that executable would be with that account.  It's running with NMMS and set to run as m domain user.  That file is a log file that ZUI creates and looks like when it archives it at night to a tar.gz file it does something to the original file and it fails to be removed.  When I try and view the permissions on that file it says there is no owner.  Happened again when I tried to look at the logs thru the GUI today.

**Comment by robertsLando** [comment] 2023-02-03 13:50
I have submitted a fix for this, at least it should not throw, the problem is that file seems is still present but when I try to get stats that error is thrown, no clue why BTW, maybe the log rotation delete doesn't completely delete the file and a dead reference remains in memory, no clue as cannot repro this on linux system

**Comment by jriker1** [comment] 2023-02-03 13:53
Odd, next day it's still complaining about the 2023-02-01.log file.  Figured it would start complaining about 2023-02-02 but looks like there are no new log files being generated.  Below is what I see at 7:53AM on 2/3/2023 CST.
![image](https://user-images.githubusercontent.com/1495536/216620512-04df850d-6f96-4cc8-ba35-e28401ebe564.png)

**Comment by spudwebb** [comment] 2024-09-12 13:54
I'm having the same problem, ZWave JS UI running on windows as admin. Everyday at midnight I get the following error, which then repeats itself every hour:

```
2024-09-11 23:18:03.519 DEBUG APP: [session-file-store] Deleting expired sessions
2024-09-11 23:18:03.566 INFO LOGGER: Cleaning up log files...
2024-09-11 23:59:59.697 INFO Z-WAVE: Next update scheduled for: Thu Sep 12 2024 00:00:00 GMT-0400 (Eastern Daylight Time)
Logging to file:
        C:\Program Files (x86)\HomeSeer HS4\Data\ZWavePlus\zwave-js-ui\store_7e62acad-7dac-4c20-b383-5d1008aaac93\logs\zwavejs_2024-09-12.log
2024-09-12 00:00:00.229 INFO Z-WAVE: Next update scheduled for: Fri Sep 13 2024 00:00:00 GMT-0400 (Eastern Daylight Time)
2024-09-12 00:18:03.417 DEBUG APP: [session-file-store] Deleting expired sessions
2024-09-12 00:18:03.479 INFO LOGGER: Cleaning up log files...
2024-09-12 00:18:03.487 ERROR LOGGER: Error getting file stats: EPERM: operation not permitted, stat 'C:\Program Files (x86)\HomeSeer HS4\Data\ZWavePlus\zwave-js-ui\store_7e62acad-7dac-4c20-b383-5d1008aaac93\logs\z-ui_2024-09-11.log'
Error: EPERM: operation not permitted, stat 'C:\Program Files (x86)\HomeSeer HS4\Data\ZWavePlus\zwave-js-ui\store_7e62acad-7dac-4c20-b383-5d1008aaac93\logs\z-ui_2024-09-11.log'
2024-09-12 01:18:03.374 DEBUG APP: [session-file-store] Deleting expired sessions
2024-09-12 01:18:03.437 INFO LOGGER: Cleaning up log files...
2024-09-12 01:18:03.440 ERROR LOGGER: Error getting file stats: EPERM: operation not permitted, stat 'C:\Program Files (x86)\HomeSeer HS4\Data\ZWavePlus\zwave-js-ui\store_7e62acad-7dac-4c20-b383-5d1008aaac93\logs\z-ui_2024-09-11.log'
Error: EPERM: operation not permitted, stat 'C:\Program Files (x86)\HomeSeer HS4\Data\ZWavePlus\zwave-js-ui\store_7e62acad-7dac-4c20-b383-5d1008aaac93\logs\z-ui_2024-09-11.log
```

It seems that after ZUI archives the z-ui log file as a gz file, it fails to delete the log file and messes up the permissions on it. I cannot open it (z-ui_2004-09-11.log) from windows explorer, but I can open the log file for the current day (z-ui_2024-09-12.log) just fine.

Also, note that it only happens for the z-ui log files, the zwavejs log files don't have this problem.

Can this issue be reopened?

**Comment by robertsLando** [comment] 2024-09-13 06:23
hi @spudwebb, the log rotation is automatically handeld by another library `@zwave-js/winston-daily-rotate-file` and I'm aware of some issues related to that expecially when it comes to delete files, in fact I have integrated my own [handler](https://github.com/zwave-js/zwave-js-ui/blob/f453187ec2050d0b64e7c7ca13dfc26e69863c8b/api/lib/logger.ts#L209) to clean up files. no clue if this is a known one. 

cc @AlCalzone @Apollon77

**Comment by AlCalzone** [comment] 2024-09-13 10:45
@robertsLando `zwave-js` has updated the file rotator back to the official version a while back. `5.0.0` should be fixed AFAIK.

**Comment by robertsLando** [comment] 2024-09-16 08:21
@AlCalzone Latest version on NPM is still 4.5.6-1: https://www.npmjs.com/package/@zwave-js/winston-daily-rotate-file

**Comment by AlCalzone** [comment] 2024-09-16 12:16
Not the scoped/forked package. The original one: https://www.npmjs.com/package/winston-daily-rotate-file

**Comment by robertsLando** [comment] 2024-09-16 13:06
LOL nice to know 😆 Does it fixes the bug related to files not being deleted? I know it used to loose the track of files on every startup so they remain there forever

**Comment by AlCalzone** [comment] 2024-09-16 15:17
I don't know. @apollon77 does it?

**Comment by Apollon77** [comment] 2024-09-16 15:48
I think not. I did not found time to look into it.

**Comment by robertsLando** [comment] 2024-09-16 16:08
For now I have merged my pr to remove the obsolete @zwave-js package, let's see if the bug reported here is fixed then or not

**Closed** 2024-09-16 16:07 UTC
Labels: bug

**Comment by spudwebb** [comment] 2024-09-27 13:05
I'm still seeing the same errors with ZWave JS UI v9.20.0

```
2024-09-27 00:00:00.111 INFO Z-WAVE: Next update scheduled for: Sat Sep 28 2024 00:00:00 GMT-0400 (Eastern Daylight Time)
2024-09-27 00:31:36.110 DEBUG APP: [session-file-store] Deleting expired sessions
2024-09-27 00:31:36.157 INFO LOGGER: Cleaning up log files...
2024-09-27 00:31:36.179 ERROR LOGGER: Error getting file stats: EPERM: operation not permitted, stat 'C:\Program Files (x86)\HomeSeer HS4\Data\ZWavePlus\zwave-js-ui\store_7e62acad-7dac-4c20-b383-5d1008aaac93\logs\z-ui_2024-09-26.log'
Error: EPERM: operation not permitted, stat 'C:\Program Files (x86)\HomeSeer HS4\Data\ZWavePlus\zwave-js-ui\store_7e62acad-7dac-4c20-b383-5d1008aaac93\logs\z-ui_2024-09-26.log'
2024-09-27 01:31:36.092 DEBUG APP: [session-file-store] Deleting expired sessions
2024-09-27 01:31:36.139 INFO LOGGER: Cleaning up log files...
2024-09-27 01:31:36.143 ERROR LOGGER: Error getting file stats: EPERM: operation not permitted, stat 'C:\Program Files (x86)\HomeSeer HS4\Data\ZWavePlus\zwave-js-ui\store_7e62acad-7dac-4c20-b383-5d1008aaac93\logs\z-ui_2024-09-26.log'
Error: EPERM: operation not permitted, stat 'C:\Program Files (x86)\HomeSeer HS4\Data\ZWavePlus\zwave-js-ui\store_7e62acad-7dac-4c20-b383-5d1008aaac93\logs\z-ui_2024-09-26.log'
2024-09-27 02:31:36.077 DEBUG APP: [session-file-store] Deleting expired sessions
```

**Comment by robertsLando** [comment] 2024-09-27 13:24
could you tell me the permissions of that file?

**Comment by spudwebb** [comment] 2024-09-27 13:36
When I try to see the permissions of that file it says I don't have read permissions on that file
![image](https://github.com/user-attachments/assets/e9184c58-578d-4f43-ba29-f18f6e962d12)
Then if I click Advanced and continue to attempt to see the permissions as Administrator it still says I don' t have permissions:
![image](https://github.com/user-attachments/assets/b9d1c45d-8653-436d-853f-dfbaf3bb7ae1)

I can' t open it, but it' s not empty, windows says it is 56KB

**Comment by robertsLando** [comment] 2024-09-27 13:42
wow cool, I have no idea how this is possible, I have a feel this is something strictly related to windows as the main issue is referencing to windows paths as well...

**Comment by robertsLando** [comment] 2024-09-27 13:44
Seems there is an open issue on nodejs related to this: https://github.com/nodejs/node/issues/35853

The question anyway could be also why the hell that file has those permissions...

**Comment by AlCalzone** [comment] 2024-09-27 13:45
How is the process executed? With any special user account or permissions?
Does the issue happen every night?

**Comment by robertsLando** [comment] 2024-09-27 13:47
@AlCalzone Just as reference, I delete the files using this script: https://github.com/zwave-js/zwave-js-ui/blob/d8c1f7b71c15a0aaec470e88b0b7e6c2bae28a7d/api/lib/logger.ts#L209

In order to fix the issue with log files never deleted

**Comment by spudwebb** [comment] 2024-09-27 14:47
> How is the process executed? With any special user account or permissions? Does the issue happen every night?

The process is executed as a child process of HomeSeer which is run with Administrator rights.  
The issue happen every night but only for the z-ui log file, the zwavejs log file is fine.

**Comment by robertsLando** [comment] 2024-09-27 14:53
yeah because actually the trick to delete the old files runs only on zui files, it's something I had to add in order to fix another issue related to the daily rotate module that doesn't delete log files under certain conditions and users ended up with tons of log files causing memory issues

**Comment by AlCalzone** [comment] 2024-10-05 08:02
> Obviously a proper fix would need to re-create the transports when the config changes like what is done in ZWaveJS but it's a bit above my typescript skills.

Good find! I can work with @robertsLando on that next week.

**Comment by robertsLando** [comment] 2024-10-07 08:06
@spudwebb thanks so much for the detailed issue! I have submit #3928, could you give it a try?
