### ISSUE TITLE
Unable to update container to :latest via watchtower

### ISSUE THREAD

**Issue by nitobuendia** [zwave-js/zwave-js-ui#2920] opened 2023-01-29 04:04 UTC
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.8.1.86d7bf4

### ZwaveJS version

10.5.0

### Describe the bug

When running watchtower to update cointainers, I get the following error:

```
Could not do a head request for "zwavejs/zwavejs2mqtt:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"
```

This did not happen before. The first occurence started on Jan 28th. It seems related to [these changes](https://github.com/containrrr/watchtower/discussions/1529#discussioncomment-4748053). For example, pihole had the same error but they fixed it. The issue also contains links to instructions on how to solve it.

### To Reproduce

Set up a container with `:latest` via docker-compose.yaml

```yaml
version: "3.7"

services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - TZ=Asia/Singapore
    env_file:
      - ./secrets.env
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # Z-Wave
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - "8091:8091" # Web interface.
      - "3000:3000" # zwave-js websocket server.
```

Set up watchtower to auto-update via docker-compose:

```yaml
version: "3"

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    env_file:
      - ./common.env
    environment:
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./run:/run
```

### Expected behavior

Container should auto-update.

**Comment by robertsLando** [comment] 2023-01-29 10:52
@nitobuendia Could you try using the new tag? `zwavejs/zwave-js-ui:latest`

**Comment by nitobuendia** [comment] 2023-01-30 13:37
@robertsLando Happy to try. I've changed the container now. However, I may not have a confirmed update until the container needs to be updated. Thanks!

**Comment by robertsLando** [comment] 2023-01-30 13:49
@nitobuendia You are welcome! Feel free to reopen in case the bug persists. BTW I neer used watchower my own so I dunno what could be the root cause as long as a docker pull works

**Comment by nitobuendia** [comment] 2023-01-30 15:29
@robertsLando I believe the issue comment I linked addresses that:

> This is due to a new format of the manifest that is produced with the new version of `docker buildx`. (...) If you are responsible for creating said image, you can look at the upstream bug for ways to opt-out of the unsupported manifest until it's supported: https://github.com/docker/buildx/issues/1509#issuecomment-1378538197

You can see an example on how this was handled for a [different container like pihole](https://github.com/pi-hole/docker-pi-hole/issues/1289).

In any case, I will update with the results as stated.

**Comment by robertsLando** [comment] 2023-01-30 15:55
So the fix should be as easy as: https://github.com/pi-hole/docker-pi-hole/pull/1290/files

**Comment by chrisns** [comment] 2023-01-31 15:49
this is an issue with watchtower
disabling `provenance` is an ugly workaround.
If watchtower don't want to fix it, then I'd suggest looking at an alternative.

suggest we close this ticket

from a philosophical basis, while @robertsLando and co work super hard to keep things stable, I'd suggest you might not want to auto update the runtime. you'd be better with using something like renovate to keep your docker compose manifest files updated with pinned releases, then you'll always have a history of what was running rather than letting watchtower autoupdate the runtime

**Comment by robertsLando** [comment] 2023-01-31 15:51
Thanks for the follow up @chrisns 🙏🏼

**Closed** 2023-01-31 15:50 UTC
Labels: bug

**Comment by nitobuendia** [comment] 2023-02-01 13:22
@robertsLando This seems to work fine with the new image. It updated today with no issues.
