### ISSUE TITLE
"[SendDataMulticastBridge]" not updating "[currentValue]" but "[targetValue]" is OK

### ISSUE THREAD

**Issue by ranonyme** [zwave-js/zwave-js-ui#3107] opened 2023-05-27 13:11 UTC
### Checklist

- [x]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.17.1

### ZwaveJS version

10.22.2

### Describe the bug

When a [SendDataMulticastBridge] is send, the currentValue of the nodes are not updated.

- If we start with this state : 

<img width="1023" alt="multicast 0 - etat depart" src="https://github.com/zwave-js/zwave-js-ui/assets/1147789/71542456-f22b-4021-82c2-8e203f38b87e">

------------------------------------------------------
- And send this command : 

<img width="963" alt="multicast 1 - action" src="https://github.com/zwave-js/zwave-js-ui/assets/1147789/9ed7d447-0c1a-4c8d-926d-8f372c5a1b41">

------------------------------------------------------
- We have this result (light is ON, targetValue is ON, but currentValue is OFF) :

<img width="1024" alt="multicast 2 - etat multicast - light is on" src="https://github.com/zwave-js/zwave-js-ui/assets/1147789/8483e480-f551-4920-ac2e-f2a0e6e1037a">

------------------------------------------------------
- If we press "refresh", everything is ok : 

<img width="1025" alt="multicast 3 - apres refresh button" src="https://github.com/zwave-js/zwave-js-ui/assets/1147789/d2cff86e-961c-4f9a-bb0f-cc9eebe809ee">

### To Reproduce

Send a [SendDataMulticastBridge] to at least 2 nodes.

### Expected behavior

We should have [currentValue] set to ON without having to press "refresh" like in older versions or like a [SendDataBridge] call.

Here is the good result with a [SendDataBridge]

- Starting point : 
<img width="1055" alt="normal 0 - etat depart" src="https://github.com/zwave-js/zwave-js-ui/assets/1147789/e48e9160-85f4-4ae6-aad0-b6313866a86f">

------------------------------------------------------
- Action : 
<img width="1201" alt="normal 1 - action" src="https://github.com/zwave-js/zwave-js-ui/assets/1147789/b4bc747b-d392-4793-b00f-3ed6711a3a06">

------------------------------------------------------
- Result : [targetValue] and [currentValue] are set ON
<img width="1054" alt="normal 2 - etat apres normal" src="https://github.com/zwave-js/zwave-js-ui/assets/1147789/cfe279d3-49ec-4e84-a7e5-44da55564738">

### Additional context

Everything was ok in older version (I don't know since when it's not ok)

**Comment by robertsLando** [comment] 2023-05-29 08:31
@ranonyme When the command is send from the UI is the current value updated correctly?

**Comment by ranonyme** [comment] 2023-05-29 09:06
Yes. From the UI it send a [SendDataBridge] and the targetValue and currentValue are well updated. No need to click "refresh".

I have this "bug" only with the [SendDataMulticastBridge] command. I say it's a "bug" because in previous version, the currentValue were updated with [SendDataMulticastBridge]. No I have to ask for a refresh for the currentValue to be updated.

**Comment by robertsLando** [comment] 2023-05-31 14:21
@ranonyme How do you trigger that command?

**Comment by robertsLando** [comment] 2023-05-31 15:09
It should but he said it's using 8.17.1

**Comment by robertsLando** [comment] 2023-05-31 15:14
Yeah it's that for sure, I thought 8.17.1 was using that. Let me make a patch

**Comment by robertsLando** [comment] 2023-05-31 17:49
@ranonyme could you try with `master` tag?

**Comment by ranonyme** [comment] 2023-05-31 18:04
Sorry I don’t know how to do that. Is there a way to do that from Home Assistant updates ?

**Comment by robertsLando** [comment] 2023-06-01 06:32
Aren't you using docker? At least that is what I see in your issue details

**Comment by ranonyme** [comment] 2023-06-01 06:43
Yes, installed from Home Assistant. Can I force un update from here ?
<img width="890" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/1147789/a5744a55-c059-4924-81f8-4c23fa55fa08">

**Comment by robertsLando** [comment] 2023-06-01 07:39
Oh that addon is not maintained by me, you have to wait Frenck to make a new release

**Comment by robertsLando** [comment] 2023-06-01 07:39
Closing this issue for now, once you can update if the issue is not solved feel free to reopen

**Closed by robertsLando** 2023-06-01 07:40 UTC
Labels: bug

**Comment by ranonyme** [comment] 2023-06-01 20:48
I can confirm everything is ok now. Thank you !
