### ISSUE TITLE
UI does not reload the page when behind an Authelia

### ISSUE THREAD

**Issue by Daniel-dev22** [zwave-js/zwave-js-ui#3518] opened 2024-01-15 11:46 UTC
**Is your feature request related to a problem? Please describe.**

I have the web UI behind authelia and when the session has expired authelia will respond to traefik with a denied request if not verified. 

I used "install app" in chrome on android to add the web UI to my phone home screen. I'm not exactly sure of the flow other than it appears that the web UI doesn't reload the page when the connection is 401 and because of that I can't re-authenticate within the same app.

Clicking return or refresh doesn't change anything the error remains the same.

![Screenshot_20240115_064337_Chrome](https://github.com/zwave-js/zwave-js-ui/assets/47092714/f1529ea7-66b7-4fe9-9b01-f7a48e8dd83e)

**Describe the solution you'd like**

I'm not sure of the technical parts I assume it needs to reload the page but I'm not sure if because I installed it as a web app that it makes it harder for it to do a refresh and redirect to the authelia login page. 

The redirect to the login page is automatic when trying to access a page behind traefik as it handles that using the forward authentication capabilities.

**Describe alternatives you've considered**

I have to go to some other app behind authelia or directly to authelia to sign in then I come back to the zwave web UI and it's working without a reload.

**Additional context**

I'm sure this isn't just an issue with Authelia and is likely an issue with all authentication providers that sit in front of the zwave web UI.

**Comment by robertsLando** [comment] 2024-01-15 13:23
Could be a duplicate of: https://github.com/zwave-js/zwave-js-ui/issues/3427 ?

**Comment by robertsLando** [comment] 2024-01-15 13:35
Unfortunately I have no solution for that yet, subscribe to that issue so you will get an update if I find one (closing this as it's a dup)

**Closed by robertsLando** 2024-01-15 13:35 UTC
Labels: enhancement
