### ISSUE TITLE
MQTT commands fail after broker restart

### ISSUE THREAD

**Issue by chrish987** [zwave-js/zwave-js-ui#3109] opened 2023-05-28 04:16 UTC
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.17.1

### ZwaveJS version

10.22.2

### Describe the bug

If i restart mosquitto then any commands sent over mqtt to zwavejs fail until zwavejs is restarted.

I am running zwave and mosquitto in separate docker containers.

My MQTT config in zwave is always manual. I have the Gateway Topic Type set to Configured Manually, and the Payload Type set to Entire z-wave value object. I then have entries added for each node. The easiest way to reproduce this is with a light (Aeon Nano Dimmer) where I have an manual entry for Target-Value (38-0-targetvalue) with a topic of dimmer-control. If I write a 99 (brightness %) value to dimmer-control/set then the light turns on.

This all works ok until I restart mosquitto.

After a restart zwavejs has no issue publishing messages to the broker, that works as expected, but any message zwavejs is expected to consume from the broker is ignored.

A restart of zwavejs fixes things.

![image](https://github.com/zwave-js/zwave-js-ui/assets/77754678/629b8767-c5ca-4424-b70a-369dd4faff27)
![image](https://github.com/zwave-js/zwave-js-ui/assets/77754678/18d83915-ae64-4f02-81ca-781a4358bd19)
![image](https://github.com/zwave-js/zwave-js-ui/assets/77754678/4faa8c20-0ff4-4bdc-8b42-bbac1ef5a3f4)

### To Reproduce

zwavejs running in a docker container
mosquitto running in a zwave container
put 99 value onto zwave-js-ui/Office/OfficeLampGlobe/dimmer-control/set topic
light turns on
put OFF value onto zwave-js-ui/Office/OfficeLampGlobe/dimmer-control/set topic
light turns off
restart mosquitto
put 99 value onto zwave-js-ui/Office/OfficeLampGlobe/dimmer-control/set topic
no action from light (value can be seen on topic however)

restart zwavejs
all works ok again

### Expected behavior

zwavejs should survive a broker restart

### Additional context

nothing in the logs.

successful log
![image](https://github.com/zwave-js/zwave-js-ui/assets/77754678/0a18b79c-e6a6-49c5-8df9-c644ebfaf923)

mosquitto restart logs.
![image](https://github.com/zwave-js/zwave-js-ui/assets/77754678/58b43141-34f4-4059-bda1-2c14fbcdea50)

nothing in the log when it fails

**Comment by robertsLando** [comment] 2023-05-29 08:33
@chrish987 Ok it could be the client is not restoring subscriptions for some reason, let me try to reproduce this on my instance

**Comment by chrish987** [comment] 2023-05-30 04:20
bit of extra info. this is not a new issue, it has been happening a long time, so potentially has always existed, not a newly introduced bug.

**Comment by robertsLando** [comment] 2023-05-31 14:27
I cannot reproduce your issue, which broker are you using?


https://github.com/zwave-js/zwave-js-ui/assets/11502495/5d8be1ee-ea55-48b9-9e91-d098614a3cc0

**Comment by chrish987** [comment] 2023-05-31 21:59
i am using mosquitto with a fairly basic config. eveything relevant to this is just running on the 1883 the other stuff is used for something else.

I did think it strange that this is not more widely reported. My thinking was that it was something to do with using manually configured topics - maybe not many people do this??

Is there any config files or anything I could send that might help.

As I said earlier this has been occurring for a long time. 3-4 months ago I moved zwavejs from running on a Pi with a zwave HAT, pulled the zwavejs back to a server and just left a zwave USB stick in the Pi using a TCP connection over ser2net. This resulted in a brand new install from scratch of zwavejs and re-enrolling all the devices. The problem existed either side of this - so I don't think it is some 'weird' config item that has crept in over many upgrades.

```
per_listener_settings true

log_type error
log_type warning
log_type notice
log_type information
log_timestamp_format %Y-%m-%dT%H:%M:%S

listener 1883
socket_domain ipv4
protocol mqtt
allow_anonymous true

listener 8883
socket_domain ipv4
protocol mqtt
allow_anonymous true
#require_certificate true
#use_identity_as_username true
cafile /mosquitto/config/certs/AmazonRootCA1.pem
keyfile /mosquitto/config/certs/hub.key
certfile /mosquitto/config/certs/hub.pem

listener 8884
socket_domain ipv4
protocol mqtt
require_certificate true
use_identity_as_username true
cafile /mosquitto/config/certs/ca.crt
keyfile /mosquitto/config/certs/server.key
certfile /mosquitto/config/certs/server.crt
```

**Comment by robertsLando** [comment] 2023-06-01 06:34
> I did think it strange that this is not more widely reported. My thinking was that it was something to do with using manually configured topics - maybe not many people do this??

Manually configured or else should not make any difference in subscriptions. Could you send me your settings?

**Comment by chrish987** [comment] 2023-06-03 05:27
Here is my settings.json file. Is this what you needed?

Do you have any mosquitto settings different to mine. My mosquitto is latest 2.0.15.

[settings.json.txt](https://github.com/zwave-js/zwave-js-ui/files/11641799/settings.json.txt)

**Comment by robertsLando** [comment] 2023-06-05 14:13
My mosquitto version is `2.0.15` like yours. Mosquitto settings are the default ones, could it be the problem only happens when the client remains offline for more then some seconds? I tested again also with gateway configured with manually mapped values like your and it's still working as expected. Are you using mosquitto bridge maybe?

**Comment by robertsLando** [comment] 2023-06-20 07:15
@chrish987 News on this?

**Comment by chrish987** [comment] 2023-06-21 21:41
I will try and recreate with a fresh install in the next couple days and capture all the steps I take.

Is it possible you can post your mosquitto config for me to compare?

It is not an issue with how long mosquitto is offline - just a restart of mosquitto causes the issue.

**Comment by robertsLando** [comment] 2023-06-22 08:08
Here you are: 

```
~$ cat /etc/mosquitto/mosquitto.conf
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d
```

I don't have anything inside `/etc/mosquitto/conf.d`

**Comment by chrish987** [comment] 2023-07-02 02:04
I don't have persistence enabled on my mosquitto - so doing some testing with that enabled.

Do you have clean sessions turned on in your zwave-js config?

**Comment by chrish987** [comment] 2023-07-02 04:28
It is (lack of) persistence that is causing the issue. I have enabled persistence in mosquitto (left clean sessions off in zwave) and I can't recreate the issue.

Not sure lack of persistance *should* break it, but I can't (yet) see any reason not to leave persistence turned on.

The only difference I can see persistence would make is that the SET topic exists as soon as mosquitto is restarted, but this still does not exist on a clean start (mosquitto first, then zwave) and it then works.

Maybe see if you can recreate with persistence off - if you think this is still a bug.

**Comment by robertsLando** [comment] 2023-07-03 09:00
> Do you have clean sessions turned on in your zwave-js config?

Yes, in general clean flag should ALWAYS be set to true to prevent unexpected memory leak issues on broker

> It is (lack of) persistence that is causing the issue. I have enabled persistence in mosquitto (left clean sessions off in zwave) and I can't recreate the issue.

You should never set the clean flag to true. I also maintain [Aedes](https://github.com/moscajs/aedes) MQTT broker and the clean flag is the most misunderstood setting and also the one that causes most issues when using MQTT. The only reason you want it to be enabled is if you want to be 100% sure a client receives ALL messages of it's subscribed topics, even the ones while it was offline. Usually this is needed when you have a client that needs to store historical values for example but that's absolutely not the case of zwave-js-ui, it just subscribe to receive commands so he have no reason to receive commands while it was offline because there could only be unexpected bahaviours with this. I suggest you to firstly set the clean flag to true and see if the issue happens

**Comment by robertsLando** [comment] 2023-08-04 12:37
@chrish987 Did you fixed this issue at the end? Can I close this? Let me know if I can help you...

**Comment by chrish987** [comment] 2023-08-06 00:21
The issue went away when I enabled persistence.

I expect there is a bug here - as I don't see that lack of persistence should break this.

That said - probably more valuable things to spend time on.

I am happy for this to be closed.

**Comment by robertsLando** [comment] 2023-08-06 06:18
As I said in my previous command there is no sense to usa a non clean session. When clean is turned off the session is persisted on broker and when it restarts, without persistence turned on, it's not able to restore it and that's the issue.

I would tell you to try to just enable clean session on zui side and disable persistence on broker side, that will work too (and it's also better)

**Closed by robertsLando** 2023-08-06 06:18 UTC
Labels: bug
