### ISSUE TITLE
Consider turning on driver logs by default (log to file)

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js-ui#3249] opened 2023-08-28 14:19 UTC
This would make it much easier to do post-mortem debugging with users without having to explain to them how to enable those, and that they need to wait or reproduce their issue.

**Comment by thecobra666** [comment] 2023-08-30 05:06
I have disabled all logs because they slowed down the storage it was running on. I only enable them when needed. 

For those running this on a raspberry pi microsd card it might also be better to keep it disabled since it creates a lot of unnecessary writes to the card.

**Comment by robertsLando** [comment] 2023-08-30 06:35
@thecobra666 making them enabled by default wouldn't make any difference for the ones that already have a configuration, it will enable them just for the once that use zui first time with no configuration saved yet

**Comment by thecobra666** [comment] 2023-08-30 06:51
> @thecobra666 making them enabled by default wouldn't make any difference for the ones that already have a configuration, it will enable them just for the once that use zui first time with no configuration saved yet

I do still stand by my point in regards to the unnecessary writes to disk. These logs, when not needed, would keep using up IO which is not needed. Enabling them when necessary should be the better option. Why not include a simple button that enables a debug 'mode' and thus sets the correct log settings
 When finished the user can disable it again and all goes back to normal.

**Comment by robertsLando** [comment] 2023-08-30 06:59
Yeah I understand you point, but from our prospective it would make easier and faster to support users, most common answer to issues is 'please make a driver/application log and attach it to the issue', this requires users to check docs and enable logs and reproduce the issue and this could be hard for newbies. Anyway if someone knows what he is doing can simply disable them when setting up zui the first time

**Comment by robertsLando** [comment] 2023-08-30 08:45
> Maybe this request is meant for the Z-Wave JS UI add-on, which disables the logging by default?

Yeah I just checked this and seems them are already enabled by default, I have no clue about how the addon can disable them by default, maybe they create a pre-configured settings file?

**Comment by robertsLando** [comment] 2023-08-30 14:42
Ok so I close this issue as should be moved/requested in the addon instead

cc @Frenck

**Closed by robertsLando** 2023-08-30 14:42 UTC
